stages:
  - build
  - docker_deploy

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# -------------------
# Build APK signé
# -------------------
build_release:
  stage: build
  image: gradle:8.10.0-jdk17-jammy
  before_script:
    - chmod +x ./gradlew
  script:
    - echo $KEYSTORE_FILE | base64 -d > my-release-key.jks
    - ./gradlew assembleRelease --stacktrace --info
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week

# -------------------
# Docker Deploy
# -------------------
docker_deploy:
  stage: docker_deploy
  image: docker:24.0.5
  services:
    - docker:dind
  needs: [build_release]
  script:
    - docker build -f Docker/Dockerfile -t myapp:latest .
    - docker stop myapp || true
    - docker rm myapp || true
    - docker run -d --name myapp -p 8080:8080 myapp:latest
