stages:
  - build
  - test
  - build-sonar
  - lint
  - dependency_check
  - docker_deploy
  - report

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

default:
  image: gradle:8.10.0-jdk17-jammy
  before_script:
    - apt-get update && apt-get install -y wget unzip curl docker.io
    - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
    - wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
    - unzip cmdtools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
    - mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
    - rm cmdtools.zip
    - export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
    - yes | sdkmanager --licenses || true
    - sdkmanager "platform-tools" "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS"
    - chmod +x ./gradlew



build:
  stage: build
  image: gradle:jdk17
  script:
    - echo $KEYSTORE_FILE | base64 -d > my-release-key.keystore
    - ./gradlew assembleRelease
  artifacts:
    paths:       
      - app/build/outputs/apk/**/*.apk
    expire_in: 1 week





# Deploy Debug in Docker
# -------------------
docker_deploy:
  stage: docker_deploy
  image: gradle:8.10.0-jdk17-jammy
  services:
    - docker:dind
  needs: [build]
  before_script:
    - apt-get update && apt-get install -y docker.io
    - chmod +x ./gradlew
  script:
    - mkdir -p docker_app
    - cp app/build/outputs/apk/release/app-release.apk docker_app/
    - echo -e "FROM openjdk:17-jdk\nCOPY app-release.apk /app-release.apk" > docker_app/Dockerfile
    - docker build -t myapp:latest docker_app/
    - docker stop myapp || true
    - docker rm myapp || true
    - docker run -d --name myapp -p 8080:8080 myapp:latest



