stages:
  - build
  - test
  - build-sonar
  - lint
  - dependency_check
  - deploy_debug
  - deploy_release
  - report

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_SDK_ROOT: "$CI_PROJECT_DIR/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"   # ← ici
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

default:
  image: gradle:8.10.0-jdk17-jammy
  before_script:
    - apt-get update && apt-get install -y wget unzip curl
    - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
    - wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
    - unzip cmdtools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
    - mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
    - rm cmdtools.zip
    - export PATH="$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
    - yes | sdkmanager --licenses || true
    - sdkmanager "platform-tools" "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS"
    - chmod +x ./gradlew

# Build APK
build:
  stage: build
  script:
    - echo "Start Build APK"
    - ./gradlew clean assembleDebug --stacktrace --info
  artifacts:
    paths:
      - app/build/outputs/
    expire_in: 1 week
  rules:
    - when: always

# Unit Tests
unit_test:
  stage: test
  needs: 
    - job: build
      optional: true
  script:
    - echo "Start Unit Tests"
    - ./gradlew testDebugUnitTest --stacktrace --info
  artifacts:
    paths:
      - app/build/test-results/
      - app/build/reports/tests/
    when: always

build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"

  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

  script:
    - echo "Start SonarQube Analysis"
    # Assure-toi que le plugin Sonar est installé dans build.gradle
    - ./gradlew sonarqube \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.host.url=$SONAR_HOST_URL \
        --stacktrace --info

  allow_failure: false   # Passe à true si tu veux que l'échec n'arrête pas le pipeline
  rules:
    - when: always


# Lint
lint_check:
  stage: lint
  needs: 
    - job: build
      optional: true   # ← idem ici
  script:
    - ./gradlew lint
  artifacts:
    paths:
      - app/build/reports/lint-results.html
    expire_in: 1 week
