# Utiliser une image de base avec JDK et Android SDK
FROM openjdk:17

# Installer dépendances nécessaires
RUN apt-get update && apt-get install -y unzip wget

# Copier l'APK généré depuis GitLab CI
WORKDIR /app
COPY build/outputs/apk/release/app-release.apk /app/app-release.apk

# Commande par défaut (ex: afficher la taille de l’APK)
CMD ["ls", "-lh", "app-release.apk"]
